[package]
name = "application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
domain = { path = "../domain" }
diagnosis-core = { path = "../diagnosis-core" }
subtitle-core = { path = "../subtitle-core" }
async-trait.workspace = true
serde_json.workspace = true
thiserror.workspace = true
