[package]
name = "api-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
application = { path = "../application" }
api-events = { path = "../api-events" }
async-stream.workspace = true
async-trait.workspace = true
futures-core.workspace = true
axum.workspace = true
dictionary-provider = { path = "../dictionary-provider" }
domain = { path = "../domain" }
hex.workspace = true
persistence-sqlite = { path = "../persistence-sqlite" }
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tower.workspace = true

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
