[package]
name = "llm-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
application = { path = "../application" }
domain = { path = "../domain" }
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
axum.workspace = true
tokio = { workspace = true, features = ["net"] }
